### ISSUE TITLE
Blowing up indexing

### ISSUE THREAD

**Issue by arj03** [ssbc/ssb-meme#1]
I'm trying this out to the image search, sadly it blows up with:

```
ssb-meme/index.js:59
    .map(n => n.replace(imgExtRegEx, '').replace(spaceCharRegex, ' '))
                ^
TypeError: n.replace is not a function
    at getMentions.filter.map.n (/home/chrx/.ssb/node_modules/ssb-meme/index.js:59:17)
    at Array.map (<anonymous>)
    at map (/home/chrx/.ssb/node_modules/ssb-meme/index.js:59:6)
    at /home/chrx/.ssb/node_modules/ssb-meme/node_modules/flumeview-search/index.js:14:16
    at reduce (/home/chrx/.ssb/node_modules/ssb-meme/node_modules/flumeview-level/index.js:90:25)
```

**Comment by arj03** [comment]
Yeah this is now fixed
